### ISSUE TITLE
Packet does not receive

### ISSUE THREAD

**Issue by TARhub** [TARhub/ShipBattle#3]
The packet is not receiving on both ends; I will be figuring out a different way to receive/send packets so both ends can send and receive.

**Comment by TheJohnLong** [comment]
Try the byte[] buffer strategy

**Comment by TARhub** [comment]
I'll czech that out; I'm still figuring out how to send to the opposite client.

**Comment by TARhub** [comment]
## This is the exception(s) thrown:

### java.net.BindException: Address already in use: JVM_Bind

```
    at java.net.DualStackPlainSocketImpl.bind0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
    at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:190)
    at java.net.ServerSocket.bind(ServerSocket.java:375)
    at java.net.ServerSocket.<init>(ServerSocket.java:237)
    at java.net.ServerSocket.<init>(ServerSocket.java:128)
    at PacketServer.run(PacketServer.java:31)
    at java.lang.Thread.run(Thread.java:745)
```

### java.net.BindException: Address already in use: JVM_Bind

```
    at java.net.DualStackPlainSocketImpl.bind0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
    at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:190)
    at java.net.ServerSocket.bind(ServerSocket.java:375)
    at java.net.ServerSocket.<init>(ServerSocket.java:237)
    at java.net.ServerSocket.<init>(ServerSocket.java:128)
    at PacketServer.run(PacketServer.java:31)
    at java.lang.Thread.run(Thread.java:745)
```
- This isn't a copy/paste error; this exception is thrown twice for the same thing.

### Exception in thread "Thread-5" Exception in thread "Thread-8" java.lang.NullPointerException

```
    at PacketServer.run(PacketServer.java:39)
    at java.lang.Thread.run(Thread.java:745)
```

### java.lang.NullPointerException

```
    at PacketServer.run(PacketServer.java:39)
    at java.lang.Thread.run(Thread.java:745)
```

Just for further reference...

**Comment by TARhub** [comment]
## This exception is thrown when player 2 ctrl-Cs out of the program while the `PacketServer` is still being run.

### java.net.SocketException: Connection reset

```
    at java.net.SocketInputStream.read(SocketInputStream.java:209)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:161)
    at java.io.BufferedReader.readLine(BufferedReader.java:324)
    at java.io.BufferedReader.readLine(BufferedReader.java:389)
    at PacketServer$PacketRunnable.run(PacketServer.java:92)
    at java.lang.Thread.run(Thread.java:745)
```

### java.net.SocketException: Connection reset

```
    at java.net.SocketInputStream.read(SocketInputStream.java:209)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:161)
    at java.io.BufferedReader.readLine(BufferedReader.java:324)
    at java.io.BufferedReader.readLine(BufferedReader.java:389)
    at PacketServer$PacketRunnable.run(PacketServer.java:92)
    at java.lang.Thread.run(Thread.java:745)
```
- This might be because there are two players?

**Comment by TheJohnLong** [comment]
[Here](http://cs.lmu.edu/~ray/notes/javanetexamples/) is a plain-text solution to networking, see if you prefer this

**Comment by TARhub** [comment]
# Things got better, but then they got _drastically_ worse.

#### Exception in thread "Thread-0" Exception in thread "main" java.lang.NullPointerException

```
at PacketRunnable.<init>(PacketRunnable.java:15)
at PacketSend$ServerConnection.<init>(PacketSend.java:70)
at PacketSend.<init>(PacketSend.java:39)
at Battleship.main(Battleship.java:25)
```

#### java.lang.NullPointerException

```
at PacketRunnable.<init>(PacketRunnable.java:15)
at PacketServer$1.run(PacketServer.java:42)
```

### This is line 15 of `PacketRunnable:`

`inFromClient = client.getInputStream();`

I'm currently attempting to fix this fatal bug. :tada: :no_good:

**Comment by TARhub** [comment]
Well, thanks to @Explosivecoin 's careful eye (and my "blindness"), this issue is proclaimed closed!
:tada: :balloon: :balloon:

**Comment by TARhub** [comment]
##### Not as bad as before, but still not receiving.

**Comment by TARhub** [comment]
# Celebration time.

After multiple trails and tribulations, the packet receives. _Somewhat_.

So technically, this issue is closed. Goodbye!

**Comment by TheJohnLong** [comment]
Playable?

**Comment by TARhub** [comment]
NOOOOOOOOOOO.

**Comment by TheJohnLong** [comment]
Lol
